# Generated by Django 5.0.5 on 2025-03-25 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoundationApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventimage', models.ImageField(upload_to='events/')),
            ],
        ),
    ]
