# Generated by Django 5.0.5 on 2025-03-25 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoundationApp', '0002_eventmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemodel',
            old_name='image',
            new_name='memberimage',
        ),
        migrations.RenameField(
            model_name='imagemodel',
            old_name='name',
            new_name='membername',
        ),
    ]
